## Latent Semantic Analysis / Indexing (LSA/LSI) Scikit-learn

Learning goals
* (A) Understand SVD using linear algebra
* (B) Apply Truncated SVD for LSI



In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


### (A) Understand SVD using linear algebra

In [2]:
import numpy as np
A = np.random.randint(low=1, high=50, size = (15,5))
A

array([[ 2, 12, 13, 17, 39],
       [29, 38,  2, 15, 43],
       [31, 10, 13, 49, 17],
       [16, 25, 36, 42, 28],
       [23, 25, 44, 32, 41],
       [48, 13,  1, 19, 35],
       [17, 17, 13, 37, 31],
       [19, 38,  9, 34, 40],
       [19, 32, 45, 22, 45],
       [ 8, 25,  8,  6, 30],
       [37,  8, 14, 38, 43],
       [14, 36, 14,  6, 31],
       [33, 31, 39, 29,  2],
       [27, 39, 35, 45, 13],
       [15,  9,  7, 36,  5]])

In [3]:
U, S, Vt = np.linalg.svd(A, full_matrices=True)
U.shape, S.shape, Vt.shape

((15, 15), (5,), (5, 5))

In [4]:
np.round(U,1)

array([[-0.2, -0.2,  0.1, -0.4, -0.1, -0.4, -0.1, -0.1, -0.4, -0. , -0.4,
        -0.1, -0.4, -0.3, -0.1],
       [-0.3, -0.4, -0.1,  0.4, -0.1, -0. , -0.1, -0.5, -0. , -0.4,  0.2,
        -0.4,  0.1, -0.1,  0.1],
       [-0.2,  0.3, -0.4, -0.1, -0.1, -0.3, -0.2, -0.2,  0.4,  0. , -0.3,
         0.1,  0.3,  0.1, -0.3],
       [-0.3,  0.2,  0.2, -0.2, -0.1,  0.6, -0.3, -0.2, -0.1,  0. ,  0.1,
         0.1,  0. , -0.3, -0.3],
       [-0.3,  0. ,  0.2, -0.3,  0.3,  0.1, -0.1,  0.1, -0.4, -0.1, -0.2,
        -0. ,  0.5,  0.4,  0.3],
       [-0.2, -0.2, -0.5,  0.3,  0.4,  0.4,  0. ,  0.1, -0. ,  0.1, -0.4,
         0.1, -0.3,  0. , -0. ],
       [-0.2,  0. , -0.1, -0.2, -0.2,  0.1,  0.9, -0.1, -0. , -0. , -0.1,
         0. ,  0.1, -0. , -0.1],
       [-0.3, -0.2, -0. ,  0.1, -0.5,  0. , -0.1,  0.7,  0.1, -0.1, -0. ,
        -0.1,  0.2, -0. , -0.1],
       [-0.3, -0.1,  0.4, -0.2,  0.3, -0. ,  0.1,  0.1,  0.7, -0.1,  0. ,
        -0.1, -0.2, -0.1,  0.1],
       [-0.2, -0.3,  0.1,  0.1, -0.1,

In [5]:
np.round(S,1)

array([222.4,  65.1,  56.8,  40.5,  33.3])

In [6]:
np.round(Vt,1)

array([[-0.4, -0.4, -0.4, -0.5, -0.5],
       [ 0.1, -0.2,  0.4,  0.5, -0.7],
       [-0.5,  0.4,  0.7, -0.4, -0.1],
       [ 0.5,  0.6, -0.2, -0.3, -0.4],
       [ 0.6, -0.5,  0.5, -0.5,  0.1]])

In [7]:
U, S, Vt = np.linalg.svd(A, full_matrices=False)
U.shape, S.shape, Vt.shape

((15, 5), (5,), (5, 5))

In [8]:
np.round(U,1)

array([[-0.2, -0.2,  0.1, -0.4, -0.1],
       [-0.3, -0.4, -0.1,  0.4, -0.1],
       [-0.2,  0.3, -0.4, -0.1, -0.1],
       [-0.3,  0.2,  0.2, -0.2, -0.1],
       [-0.3,  0. ,  0.2, -0.3,  0.3],
       [-0.2, -0.2, -0.5,  0.3,  0.4],
       [-0.2,  0. , -0.1, -0.2, -0.2],
       [-0.3, -0.2, -0. ,  0.1, -0.5],
       [-0.3, -0.1,  0.4, -0.2,  0.3],
       [-0.2, -0.3,  0.1,  0.1, -0.1],
       [-0.3, -0.1, -0.4, -0.2,  0.3],
       [-0.2, -0.3,  0.2,  0.3, -0.1],
       [-0.3,  0.4,  0.2,  0.4,  0.3],
       [-0.3,  0.4,  0.1,  0.3, -0.2],
       [-0.1,  0.3, -0.2, -0. , -0.3]])

In [9]:
np.round(S,1)

array([222.4,  65.1,  56.8,  40.5,  33.3])

In [10]:
np.round(Vt,1)

array([[-0.4, -0.4, -0.4, -0.5, -0.5],
       [ 0.1, -0.2,  0.4,  0.5, -0.7],
       [-0.5,  0.4,  0.7, -0.4, -0.1],
       [ 0.5,  0.6, -0.2, -0.3, -0.4],
       [ 0.6, -0.5,  0.5, -0.5,  0.1]])

### (B) TruncatedSVD

In [11]:
import numpy as np
A = np.random.randint(low=1, high=50, size=(5,10))
A

array([[40, 21, 44, 25, 20,  4, 20,  8,  7,  4],
       [ 9, 40, 32, 43,  2, 36, 48, 14, 39, 29],
       [25, 20, 30, 28, 28,  1, 20,  8, 30, 32],
       [32, 46, 31, 48, 36, 37, 25, 48, 22, 14],
       [14, 30,  8, 42, 40, 37, 15, 47, 34,  2]])

In [12]:
from sklearn.decomposition import TruncatedSVD

# Create SVD object
svd = TruncatedSVD(n_components=3, n_iter=10, random_state=2)
svd.fit(A)


TruncatedSVD(n_components=3, n_iter=10, random_state=2)

In [13]:
np.round(svd.components_,2)

array([[ 0.26,  0.38,  0.32,  0.44,  0.29,  0.3 ,  0.3 ,  0.32,  0.31,
         0.18],
       [-0.25,  0.02, -0.51,  0.05,  0.24,  0.35, -0.28,  0.55, -0.  ,
        -0.34],
       [-0.55,  0.1 , -0.24,  0.06, -0.47,  0.32,  0.34, -0.15,  0.32,
         0.25]])

In [14]:
# Get Singular values and Components
Sigma = svd.singular_values_
np.round(Sigma,1)

array([193.5,  58.4,  49.4])

In [15]:
np.round(svd.explained_variance_ratio_,2)

array([0.19, 0.4 , 0.29])

In [16]:
svd.explained_variance_ratio_.sum()

0.8781451657775353

In [17]:
from sklearn.utils.extmath import randomized_svd
U, Sigma, VT = randomized_svd(A,
                              n_components=3,
                              random_state=2)

In [18]:
A.shape, U.shape, Sigma.shape, VT.shape

((5, 10), (5, 3), (3,), (3, 10))

In [19]:
np.round(U,1)

array([[ 0.3, -0.5, -0.6],
       [ 0.5, -0.3,  0.8],
       [ 0.4, -0.4, -0.1],
       [ 0.6,  0.3, -0.2],
       [ 0.5,  0.7, -0. ]])

In [20]:
np.round(Sigma,1)

array([193.5,  58.4,  49.4])

In [21]:
np.round(VT,1)

array([[ 0.3,  0.4,  0.3,  0.4,  0.3,  0.3,  0.3,  0.3,  0.3,  0.2],
       [-0.2,  0. , -0.5,  0.1,  0.2,  0.4, -0.3,  0.5, -0. , -0.3],
       [-0.5,  0.1, -0.2,  0.1, -0.5,  0.3,  0.3, -0.1,  0.3,  0.3]])

### (C) Pre-processing

In [23]:
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth', -1)
path = '/content/gdrive/My Drive/data/gensim'
train = pd.read_csv(path + "/ag_news_train.csv")

<ipython-input-23-161f11a79169>:3: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)


In [24]:
# Class Index = 1 is World
train[train['Class Index']==1][0:2]

Class Index  \
492  1             
493  1             

                                                             Title  \
492  Venezuelans Vote Early in Referendum on Chavez Rule (Reuters)   
493  S.Koreans Clash with Police on Iraq Troop Dispatch (Reuters)    

                                                                                                                                                                                                                                Description  
492  Reuters - Venezuelans turned out early\and in large numbers on Sunday to vote in a historic referendum\that will either remove left-wing President Hugo Chavez from\office or give him a new mandate to govern for the next two\years.  
493  Reuters - South Korean police used water cannon in\central Seoul Sunday to disperse at least 7,000 protesters\urging the government to reverse a controversial decision to\send more troops to Iraq.

In [25]:
# Class Index = 2 is Sports
train[train['Class Index']==2][0:2]

Class Index                                         Title  \
448  2            Phelps, Thorpe Advance in 200 Freestyle (AP)   
449  2            Reds Knock Padres Out of Wild-Card Lead (AP)   

                                                                                                                                                                                                                                                                                                                                                  Description  
448  AP - Michael Phelps took care of qualifying for the Olympic 200-meter freestyle semifinals Sunday, and then found out he had been added to the American team for the evening's 400 freestyle relay final. Phelps' rivals Ian Thorpe and Pieter van den Hoogenband and teammate Klete Keller were faster than the teenager in the 200 free preliminaries.  
449  AP - Wily Mo Pena homered twice and drove in four runs, helping the Cincinnati Reds beat the San Diego Padres 11-5 on Saturday night. San Diego was knocked out of a share of the NL wild-card lead with the loss and Chicago's victory over Los Angeles earlier in the day.

In [26]:
# Class Index = 3 is Business
train[train['Class Index']==3][0:2]

Class Index                                                Title  \
0  3            Wall St. Bears Claw Back Into the Black (Reuters)     
1  3            Carlyle Looks Toward Commercial Aerospace (Reuters)   

                                                                                                                                                                                                              Description  
0  Reuters - Short-sellers, Wall Street's dwindling\band of ultra-cynics, are seeing green again.                                                                                                                          
1  Reuters - Private investment firm Carlyle Group,\which has a reputation for making well-timed and occasionally\controversial plays in the defense industry, has quietly placed\its bets on another part of the market.

In [27]:
# Class Index = 4 is Sci/Tech.
train[train['Class Index']==4][0:2]

Class Index                                                        Title  \
78  4            'Madden,' 'ESPN' Football Score in Different Ways (Reuters)   
79  4            Group to Propose New High-Speed Wireless Format (Reuters)     

                                                                                                                                                                                                                                                               Description  
78  Reuters - Was absenteeism a little high\on Tuesday among the guys at the office? EA Sports would like\to think it was because "Madden NFL 2005" came out that day,\and some fans of the football simulation are rabid enough to\take a sick day to play it.             
79  Reuters - A group of technology companies\including Texas Instruments Inc. (TXN.N), STMicroelectronics\(STM.PA) and Broadcom Corp. (BRCM.O), on Thursday said they\will propose a new wireless networking standard up to 10 times\the speed of the current generation.

### Pre-processing

In [28]:
import os
import pandas as pd
from nltk.tokenize import RegexpTokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

In [29]:
B = train['Description'][0:5]
B

0    Reuters - Short-sellers, Wall Street's dwindling\band of ultra-cynics, are seeing green again.                                                                                                                        
1    Reuters - Private investment firm Carlyle Group,\which has a reputation for making well-timed and occasionally\controversial plays in the defense industry, has quietly placed\its bets on another part of the market.
2    Reuters - Soaring crude prices plus worries\about the economy and the outlook for earnings are expected to\hang over the stock market next week during the depth of the\summer doldrums.                              
3    Reuters - Authorities have halted oil export\flows from the main pipeline in southern Iraq after\intelligence showed a rebel militia could strike\infrastructure, an oil official said on Saturday.                   
4    AFP - Tearaway world oil prices, toppling records and straining wallets, present a new economic menace barely three

In [30]:
# Initialize regex tokenizer
tokenizer = RegexpTokenizer(r'\w+')

# Vectorize document using TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(lowercase=True,
                       stop_words='english',
                       ngram_range = (1,1),
                       tokenizer = tokenizer.tokenize)


# Fit and Transform the documents
train_data = tfidf.fit_transform(B)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [31]:
len(tfidf.get_feature_names_out())

77

In [32]:
terms = tfidf.get_feature_names_out()
terms

array(['afp', 'authorities', 'band', 'barely', 'bets', 'carlyle',
       'controversial', 'crude', 'cynics', 'defense', 'depth', 'doldrums',
       'dwindling', 'earnings', 'economic', 'economy', 'elections',
       'expected', 'export', 'firm', 'flows', 'green', 'group', 'halted',
       'hang', 'industry', 'infrastructure', 'intelligence', 'investment',
       'iraq', 'main', 'making', 'market', 'menace', 'militia', 'months',
       'new', 'occasionally', 'official', 'oil', 'outlook', 'pipeline',
       'placed', 'plays', 'plus', 'present', 'presidential', 'prices',
       'private', 'quietly', 'rebel', 'records', 'reputation', 'reuters',
       's', 'said', 'saturday', 'seeing', 'sellers', 'short', 'showed',
       'soaring', 'southern', 'stock', 'straining', 'street', 'strike',
       'summer', 'tearaway', 'timed', 'toppling', 'ultra', 'wall',
       'wallets', 'week', 'world', 'worries'], dtype=object)

In [33]:
# Create SVD object
lsi = TruncatedSVD(n_components=3, n_iter=100, random_state=42)

# Fit SVD model on data
lsi.fit(train_data)


TruncatedSVD(n_components=3, n_iter=100, random_state=42)

In [34]:
# Get Singular values and Components
Sigma = lsi.singular_values_
Sigma

array([1.05609076, 1.01734796, 0.99447695])

In [35]:
lsi.explained_variance_ratio_.sum()

0.5229249537209735

In [36]:
V_transpose = lsi.components_
V_transpose

array([[ 0.11658396,  0.10653371,  0.07814384,  0.11658396,  0.0911447 ,
         0.0911447 ,  0.0911447 ,  0.12366413,  0.07814384,  0.0911447 ,
         0.12366413,  0.12366413,  0.07814384,  0.12366413,  0.11658396,
         0.12366413,  0.11658396,  0.12366413,  0.10653371,  0.0911447 ,
         0.10653371,  0.07814384,  0.0911447 ,  0.10653371,  0.12366413,
         0.0911447 ,  0.10653371,  0.10653371,  0.0911447 ,  0.10653371,
         0.10653371,  0.0911447 ,  0.17330641,  0.11658396,  0.10653371,
         0.11658396,  0.11658396,  0.0911447 ,  0.10653371,  0.26596066,
         0.12366413,  0.10653371,  0.0911447 ,  0.0911447 ,  0.12366413,
         0.11658396,  0.11658396,  0.19383064,  0.0911447 ,  0.0911447 ,
         0.10653371,  0.11658396,  0.0911447 ,  0.22506366,  0.07814384,
         0.10653371,  0.10653371,  0.07814384,  0.07814384,  0.07814384,
         0.10653371,  0.12366413,  0.10653371,  0.12366413,  0.11658396,
         0.07814384,  0.10653371,  0.12366413,  0.1

In [37]:
V_transpose.shape

(3, 77)

In [38]:
from sklearn.utils.extmath import randomized_svd
U, Sigma, VT = randomized_svd(train_data,
                              n_components=3,
                              random_state=2)

In [39]:
train_data.shape, U.shape, Sigma.shape, VT.shape

((5, 77), (5, 3), (3,), (3, 77))

In [40]:
U.shape

(5, 3)

In [41]:
Sigma.shape

(3,)

In [42]:
VT.shape

(3, 77)

In [43]:
lsi.components_.shape

(3, 77)

In [44]:
U

array([[ 0.27763189,  0.32523121,  0.86426989],
       [ 0.39650809,  0.55894231, -0.25313875],
       [ 0.51614867,  0.3319357 , -0.3493173 ],
       [ 0.50216283, -0.44204626,  0.21839935],
       [ 0.49711659, -0.52556821, -0.13869924]])

In [45]:
VT

array([[ 0.11658396,  0.10653371,  0.07814384,  0.11658396,  0.0911447 ,
         0.0911447 ,  0.0911447 ,  0.12366413,  0.07814384,  0.0911447 ,
         0.12366413,  0.12366413,  0.07814384,  0.12366413,  0.11658396,
         0.12366413,  0.11658396,  0.12366413,  0.10653371,  0.0911447 ,
         0.10653371,  0.07814384,  0.0911447 ,  0.10653371,  0.12366413,
         0.0911447 ,  0.10653371,  0.10653371,  0.0911447 ,  0.10653371,
         0.10653371,  0.0911447 ,  0.17330641,  0.11658396,  0.10653371,
         0.11658396,  0.11658396,  0.0911447 ,  0.10653371,  0.26596066,
         0.12366413,  0.10653371,  0.0911447 ,  0.0911447 ,  0.12366413,
         0.11658396,  0.11658396,  0.19383064,  0.0911447 ,  0.0911447 ,
         0.10653371,  0.11658396,  0.0911447 ,  0.22506366,  0.07814384,
         0.10653371,  0.10653371,  0.07814384,  0.07814384,  0.07814384,
         0.10653371,  0.12366413,  0.10653371,  0.12366413,  0.11658396,
         0.07814384,  0.10653371,  0.12366413,  0.1

In [46]:
VT_names = pd.DataFrame(VT, columns=terms).round(2)
VT_names

afp  authorities  band  barely  bets  carlyle  controversial  crude  \
0  0.12  0.11         0.08  0.12    0.09  0.09     0.09           0.12    
1 -0.13 -0.10         0.10 -0.13    0.13  0.13     0.13           0.08    
2 -0.03  0.05         0.26 -0.03   -0.06 -0.06    -0.06          -0.09    

   cynics  defense  ...  summer  tearaway  timed  toppling  ultra  wall  \
0  0.08    0.09     ...  0.12    0.12      0.09   0.12      0.08   0.08   
1  0.10    0.13     ...  0.08   -0.13      0.13  -0.13      0.10   0.10   
2  0.26   -0.06     ... -0.09   -0.03     -0.06  -0.03      0.26   0.26   

   wallets  week  world  worries  
0  0.12     0.12  0.12   0.12     
1 -0.13     0.08 -0.13   0.08     
2 -0.03    -0.09 -0.03  -0.09     

[3 rows x 77 columns]

In [47]:
VT_names[0:1].sort_values(by=0, axis=1, ascending=False)

oil  reuters  prices  market  wallets  presidential  menace  months   new  \
0  0.27  0.23     0.19    0.17    0.12     0.12          0.12    0.12    0.12   

   world  ...  cynics  street  seeing  green     s  ultra  wall  dwindling  \
0  0.12   ...  0.08    0.08    0.08    0.08   0.08  0.08   0.08  0.08        

   band  short  
0  0.08  0.08   

[1 rows x 77 columns]

In [48]:
VT_names[1:2].sort_values(by=1, axis=1, ascending=False)

market  industry  timed  private  reputation  plays  placed  occasionally  \
1  0.17    0.13      0.13   0.13     0.13        0.13   0.13    0.13           

   making  investment  ...  records  straining  tearaway  presidential  \
1  0.13    0.13        ... -0.13    -0.13      -0.13     -0.13           

   menace  months   new  present   afp   oil  
1 -0.13   -0.13   -0.13 -0.13    -0.13 -0.26  

[1 rows x 77 columns]

In [49]:
VT_names[2:3].sort_values(by=2, axis=1, ascending=False)

seeing  cynics     s  sellers  short  dwindling  street  ultra  wall  band  \
2  0.26    0.26    0.26  0.26     0.26   0.26       0.26    0.26   0.26  0.26   

   ...  earnings  stock  soaring  economy  outlook  hang  plus  worries  \
2  ... -0.09     -0.09  -0.09    -0.09    -0.09    -0.09 -0.09 -0.09      

   prices  market  
2 -0.1    -0.12    

[1 rows x 77 columns]

In [50]:
# Print the topics with their terms
for index, component in enumerate(lsi.components_):
    zipped = zip(terms, component)
    top_terms_key=sorted(zipped, key = lambda t: t[1], reverse=True)[:5]
    top_terms_list=list(dict(top_terms_key).keys())
    print("Topic "+str(index)+": ",top_terms_list)

Topic 0:  ['oil', 'reuters', 'prices', 'market', 'crude']
Topic 1:  ['market', 'bets', 'carlyle', 'controversial', 'defense']
Topic 2:  ['cynics', 'dwindling', 'green', 's', 'seeing']
